### ISSUE TITLE
Python 3.4 and 3.7 broken in Linux build

### ISSUE THREAD

**Issue by rolyp** [alan-turing-institute/esig#34]
Python 3.4 no longer seems to be included out-of-the-box with our [`manylinux1`](https://quay.io/repository/pypa/manylinux1_i686?tag=latest&tab=tags) base images. Removed from `python_versions.txt` for now.

The build also now fails with Python 3.7:
`ERROR: auditwheel 3.1.0 has requirement wheel==0.34.1, but you’ll have wheel 0.31.1 which is incompatible.`

- [x] try rolling back to tag `2020-01-31-d8fa357`
- [x] reinstate 3.4 in `python_versions.txt`

**Comment by terrylyons** [comment]
There are actually a few tools that used it.
